/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminLoginResult = { 'ok' : string } |
  { 'err' : string };
export type Category = { 'bag' : null } |
  { 'cap' : null } |
  { 'tshirt' : null };
export type ContactId = bigint;
export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : ContactId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface CreateProductInput {
  'featured' : boolean,
  'stockQty' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export interface Product {
  'id' : ProductId,
  'featured' : boolean,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export interface ProductFilter {
  'sortOrder' : [] | [SortOrder],
  'category' : [] | [Category],
  'searchQuery' : [] | [string],
}
export type ProductId = bigint;
export type SortOrder = { 'featured' : null } |
  { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null };
export type Timestamp = bigint;
export interface UpdateProductInput {
  'id' : ProductId,
  'featured' : boolean,
  'stockQty' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, CreateProductInput], Product>,
  'adminLogin' : ActorMethod<[string, string], AdminLoginResult>,
  'deleteProduct' : ActorMethod<[string, ProductId], boolean>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listContactSubmissions' : ActorMethod<[string], Array<ContactSubmission>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'submitContactForm' : ActorMethod<[ContactInput], ContactSubmission>,
  'updateProduct' : ActorMethod<[string, UpdateProductInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];