/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'bag' : IDL.Null,
  'cap' : IDL.Null,
  'tshirt' : IDL.Null,
});
export const CreateProductInput = IDL.Record({
  'featured' : IDL.Bool,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const AdminLoginResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const SortOrder = IDL.Variant({
  'featured' : IDL.Null,
  'newest' : IDL.Null,
  'priceDesc' : IDL.Null,
  'priceAsc' : IDL.Null,
});
export const ProductFilter = IDL.Record({
  'sortOrder' : IDL.Opt(SortOrder),
  'category' : IDL.Opt(Category),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UpdateProductInput = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, CreateProductInput], [Product], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], []),
  'deleteProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listContactSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'submitContactForm' : IDL.Func([ContactInput], [ContactSubmission], []),
  'updateProduct' : IDL.Func([IDL.Text, UpdateProductInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'bag' : IDL.Null,
    'cap' : IDL.Null,
    'tshirt' : IDL.Null,
  });
  const CreateProductInput = IDL.Record({
    'featured' : IDL.Bool,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const AdminLoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ContactId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const SortOrder = IDL.Variant({
    'featured' : IDL.Null,
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  const ProductFilter = IDL.Record({
    'sortOrder' : IDL.Opt(SortOrder),
    'category' : IDL.Opt(Category),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UpdateProductInput = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, CreateProductInput], [Product], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], []),
    'deleteProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listContactSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'submitContactForm' : IDL.Func([ContactInput], [ContactSubmission], []),
    'updateProduct' : IDL.Func([IDL.Text, UpdateProductInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };