/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductFilter {
    sortOrder?: SortOrder;
    category?: Category;
    searchQuery?: string;
}
export interface ContactInput {
    name: string;
    email: string;
    message: string;
}
export type Timestamp = bigint;
export interface ContactSubmission {
    id: ContactId;
    name: string;
    createdAt: Timestamp;
    email: string;
    message: string;
}
export type AdminLoginResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type ProductId = bigint;
export type ContactId = bigint;
export interface CreateProductInput {
    featured: boolean;
    stockQty: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: number;
}
export interface Product {
    id: ProductId;
    featured: boolean;
    stockQty: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    imageUrl: string;
    category: Category;
    price: number;
}
export interface UpdateProductInput {
    id: ProductId;
    featured: boolean;
    stockQty: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: number;
}
export enum Category {
    bag = "bag",
    cap = "cap",
    tshirt = "tshirt"
}
export enum SortOrder {
    featured = "featured",
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc"
}
export interface backendInterface {
    addProduct(token: string, input: CreateProductInput): Promise<Product>;
    adminLogin(email: string, password: string): Promise<AdminLoginResult>;
    deleteProduct(token: string, id: ProductId): Promise<boolean>;
    getProduct(id: ProductId): Promise<Product | null>;
    listContactSubmissions(token: string): Promise<Array<ContactSubmission>>;
    listProducts(filter: ProductFilter): Promise<Array<Product>>;
    submitContactForm(input: ContactInput): Promise<ContactSubmission>;
    updateProduct(token: string, input: UpdateProductInput): Promise<boolean>;
}
import type { AdminLoginResult as _AdminLoginResult, Category as _Category, CreateProductInput as _CreateProductInput, Product as _Product, ProductFilter as _ProductFilter, ProductId as _ProductId, SortOrder as _SortOrder, Timestamp as _Timestamp, UpdateProductInput as _UpdateProductInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: string, arg1: CreateProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, to_candid_CreateProductInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, to_candid_CreateProductInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<AdminLoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_AdminLoginResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_AdminLoginResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: string, arg1: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0, arg1);
            return result;
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContactSubmissions(arg0: string): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactSubmissions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactSubmissions(arg0);
            return result;
        }
    }
    async listProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: ContactInput): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: UpdateProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_UpdateProductInput_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_UpdateProductInput_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminLoginResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminLoginResult): AdminLoginResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    featured: boolean;
    stockQty: bigint;
    name: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    imageUrl: string;
    category: _Category;
    price: number;
}): {
    id: ProductId;
    featured: boolean;
    stockQty: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    imageUrl: string;
    category: Category;
    price: number;
} {
    return {
        id: value.id,
        featured: value.featured,
        stockQty: value.stockQty,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bag: null;
} | {
    cap: null;
} | {
    tshirt: null;
}): Category {
    return "bag" in value ? Category.bag : "cap" in value ? Category.cap : "tshirt" in value ? Category.tshirt : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductInput): _CreateProductInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductInput): _UpdateProductInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortOrder?: SortOrder;
    category?: Category;
    searchQuery?: string;
}): {
    sortOrder: [] | [_SortOrder];
    category: [] | [_Category];
    searchQuery: [] | [string];
} {
    return {
        sortOrder: value.sortOrder ? candid_some(to_candid_SortOrder_n14(_uploadFile, _downloadFile, value.sortOrder)) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value.category)) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    featured: boolean;
    stockQty: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: number;
}): {
    id: _ProductId;
    featured: boolean;
    stockQty: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: number;
} {
    return {
        id: value.id,
        featured: value.featured,
        stockQty: value.stockQty,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featured: boolean;
    stockQty: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: number;
}): {
    featured: boolean;
    stockQty: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: number;
} {
    return {
        featured: value.featured,
        stockQty: value.stockQty,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    featured: null;
} | {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} {
    return value == SortOrder.featured ? {
        featured: null
    } : value == SortOrder.newest ? {
        newest: null
    } : value == SortOrder.priceDesc ? {
        priceDesc: null
    } : value == SortOrder.priceAsc ? {
        priceAsc: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    bag: null;
} | {
    cap: null;
} | {
    tshirt: null;
} {
    return value == Category.bag ? {
        bag: null
    } : value == Category.cap ? {
        cap: null
    } : value == Category.tshirt ? {
        tshirt: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
